### ISSUE TITLE
Write and test autonomous command

### ISSUE THREAD

**Issue by snowpuppy** [Team1100/FRCRapidReact#5]
Write an autonomous command that performs the following sequence:
1. Shoot ball
2. Drive backwards
3. Pick up ball
4. Drive forwards
5. Shoot ball
6. Drive backwards

**Comment by snowpuppy** [comment]
Note that the autonomous command NEEDs to be set in the RobotContainer so that we have it ready for the competition.

**Comment by JackTWing** [comment]
I am starting to work on this on my local machine
